name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.19.1, 20.19.2, 22.1.0] # Use exact versions that exist at nodejs.org

    steps:
    - uses: actions/checkout@v4

    - name: Download and extract Node.js ${{ matrix.node-version }}
      run: |
        curl -o node.7z https://nodejs.org/dist/v${{ matrix.node-version }}/node-v${{ matrix.node-version }}-win-x64.7z
        "C:\Program Files\7-Zip\7z.exe" x node.7z -oC:\nodejs
        echo "C:\nodejs\node-v${{ matrix.node-version }}-win-x64" >> %GITHUB_PATH%
      shell: cmd

    - name: Verify Node.js version
      run: node -v
      shell: cmd

    - name: Install dependencies
      run: npm ci
      shell: cmd

    - name: Build the project
      run: npm run build --if-present
      shell: cmd